server:
  port: '8090'

spring:
  profiles:
    active: dev


---


spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ishapp
    password: password
  jpa:
    show-url: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Hello World!


---

spring:
  profiles: ish
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ishapp
    password: password
  jpa:
    show-url: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Hello World!
